# Use the official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the Python script and any required files
COPY . .

# Run requirement
RUN pip install -r requirements.txt

# Run the script
CMD ["python", "Parse_Fixed_Width"]